In [1]:
import numpy as np
import matplotlib.pyplot as plt
import polars as pl

import requests
from pprint import pprint

from pathlib import Path

import json

In [21]:
import polars as pl

In [13]:
base_url = "https://fantasy.premierleague.com/api"
response = requests.get(f"{base_url}/bootstrap-static")
data = response.json()

if response.status_code == 200:
    data = response.json()
else:
    print(f"Request failed. Error: {response.text}")


Path("../bootrap-static_2026-09-03.json").write_text(json.dumps(data, indent=2))

2436203

In [14]:
for key in data:
    print(key)

chips
events
game_settings
game_config
phases
teams
total_players
element_stats
element_types
elements

In [15]:
data["game_settings"]

{'league_join_private_max': 30,
 'league_join_public_max': 5,
 'league_max_size_public_classic': 20,
 'league_max_size_public_h2h': 20,
 'league_max_size_private_h2h': 16,
 'league_max_ko_rounds_private_h2h': 3,
 'league_prefix_public': 'League',
 'league_points_h2h_win': 3,
 'league_points_h2h_lose': 0,
 'league_points_h2h_draw': 1,
 'league_ko_first_instead_of_random': False,
 'cup_start_event_id': None,
 'cup_stop_event_id': None,
 'cup_qualifying_method': None,
 'cup_type': None,
 'featured_entries': [],
 'element_sell_at_purchase_price': False,
 'percentile_ranks': [1,
  5,
  10,
  15,
  20,
  25,
  30,
  35,
  40,
  45,
  50,
  55,
  60,
  65,
  70,
  75,
  80,
  85,
  90,
  95],
 'underdog_differential': 5,
 'squad_squadplay': 11,
 'squad_squadsize': 15,
 'squad_special_min': None,
 'squad_special_max': None,
 'squad_team_limit': 3,
 'squad_total_spend': 1000,
 'ui_currency_multiplier': 10,
 'ui_use_special_shirts': False,
 'ui_special_shirt_exclusions': [],
 'stats_form_days': 30,
 'sys_vice_captain_enabled': True,
 'transfers_cap': 20,
 'transfers_sell_on_fee': 0.5,
 'max_extra_free_transfers': 4,
 'league_h2h_tiebreak_stats': ['+goals_scored', '-goals_conceded'],
 'timezone': 'UTC'}

In [16]:
chips = data["chips"]
chips[0:3]

[{'id': 1,
  'name': 'wildcard',
  'number': 1,
  'start_event': 2,
  'stop_event': 19,
  'chip_type': 'transfer',
  'overrides': {'rules': {},
   'scoring': {},
   'element_types': [],
   'pick_multiplier': None}},
 {'id': 2,
  'name': 'wildcard',
  'number': 1,
  'start_event': 20,
  'stop_event': 38,
  'chip_type': 'transfer',
  'overrides': {'rules': {},
   'scoring': {},
   'element_types': [],
   'pick_multiplier': None}},
 {'id': 3,
  'name': 'freehit',
  'number': 1,
  'start_event': 2,
  'stop_event': 19,
  'chip_type': 'transfer',
  'overrides': {'rules': {},
   'scoring': {},
   'element_types': [],
   'pick_multiplier': None}}]

In [17]:
events = data["events"]
events[:3]

[{'id': 1,
  'name': 'Gameweek 1',
  'deadline_time': '2026-08-21T17:30:00Z',
  'release_time': None,
  'average_entry_score': 50,
  'finished': True,
  'data_checked': True,
  'highest_scoring_entry': 120245,
  'deadline_time_epoch': 1787333400,
  'deadline_time_game_offset': 0,
  'highest_score': 131,
  'is_previous': True,
  'is_current': False,
  'is_next': False,
  'cup_leagues_created': False,
  'h2h_ko_matches_created': False,
  'can_enter': False,
  'can_manage': False,
  'released': True,
  'ranked_count': 8903411,
  'overrides': {'rules': {},
   'scoring': {},
   'element_types': [],
   'pick_multiplier': None},
  'chip_plays': [{'chip_name': 'bboost', 'num_played': 814606},
   {'chip_name': '3xc', 'num_played': 250816}],
  'most_selected': 411,
  'most_transferred_in': 1,
  'top_element': 115,
  'top_element_info': {'id': 115, 'points': 17},
  'transfers_made': 0,
  'most_captained': 411,
  'most_vice_captained': 1},
 {'id': 2,
  'name': 'Gameweek 2',
  'deadline_time': '2026-08-28T17:30:00Z',
  'release_time': None,
  'average_entry_score': 81,
  'finished': True,
  'data_checked': True,
  'highest_scoring_entry': 2241815,
  'deadline_time_epoch': 1787938200,
  'deadline_time_game_offset': 0,
  'highest_score': 161,
  'is_previous': False,
  'is_current': True,
  'is_next': False,
  'cup_leagues_created': True,
  'h2h_ko_matches_created': True,
  'can_enter': False,
  'can_manage': False,
  'released': True,
  'ranked_count': 9904815,
  'overrides': {'rules': {},
   'scoring': {},
   'element_types': [],
   'pick_multiplier': None},
  'chip_plays': [{'chip_name': 'bboost', 'num_played': 338660},
   {'chip_name': 'freehit', 'num_played': 78863},
   {'chip_name': 'wildcard', 'num_played': 279227},
   {'chip_name': '3xc', 'num_played': 233946}],
  'most_selected': 165,
  'most_transferred_in': 115,
  'top_element': 426,
  'top_element_info': {'id': 426, 'points': 23},
  'transfers_made': 11562127,
  'most_captained': 411,
  'most_vice_captained': 1},
 {'id': 3,
  'name': 'Gameweek 3',
  'deadline_time': '2026-09-04T17:30:00Z',
  'release_time': None,
  'average_entry_score': 0,
  'finished': False,
  'data_checked': False,
  'highest_scoring_entry': None,
  'deadline_time_epoch': 1788543000,
  'deadline_time_game_offset': 0,
  'highest_score': None,
  'is_previous': False,
  'is_current': False,
  'is_next': True,
  'cup_leagues_created': True,
  'h2h_ko_matches_created': True,
  'can_enter': True,
  'can_manage': True,
  'released': True,
  'ranked_count': 0,
  'overrides': {'rules': {},
   'scoring': {},
   'element_types': [],
   'pick_multiplier': None},
  'chip_plays': [],
  'most_selected': None,
  'most_transferred_in': None,
  'top_element': None,
  'top_element_info': None,
  'transfers_made': 0,
  'most_captained': None,
  'most_vice_captained': None}]

In [18]:
players = data['elements']

In [19]:
players

[{'can_transact': True,
  'can_select': True,
  'chance_of_playing_next_round': None,
  'chance_of_playing_this_round': None,
  'code': 154561,
  'cost_change_event': 0,
  'cost_change_event_fall': 0,
  'cost_change_start': 0,
  'cost_change_start_fall': 0,
  'price_change_percent': '9.3',
  'price_change_hourly_rate': -98,
  'price_change_projections': [{'offset': 0,
    'projected_percent': '8.6',
    'likelihood': 1},
   {'offset': 1, 'projected_percent': '7.3', 'likelihood': 1},
   {'offset': 2, 'projected_percent': '6.0', 'likelihood': 1}],
  'price_change_locked_until': None,
  'price_change_calibrating': False,
  'dreamteam_count': 0,
  'element_type': 1,
  'ep_next': '6.0',
  'ep_this': '6.0',
  'event_points': 6,
  'first_name': 'David',
  'form': '6.0',
  'id': 1,
  'in_dreamteam': False,
  'news': '',
  'news_added': None,
  'now_cost': 60,
  'photo': '154561.jpg',
  'points_per_game': '6.0',
  'removed': False,
  'second_name': 'Raya Martín',
  'selected_by_percent': '37.8',
  'special': False,
  'squad_number': None,
  'status': 'a',
  'team': 1,
  'team_code': 3,
  'total_points': 12,
  'transfers_in': 250943,
  'transfers_in_event': 144209,
  'transfers_out': 235551,
  'transfers_out_event': 153573,
  'value_form': '1.0',
  'value_season': '2.0',
  'web_name': 'Raya',
  'known_name': '',
  'region': 200,
  'team_join_date': '2024-07-04',
  'birth_date': '1995-09-15',
  'has_temporary_code': False,
  'opta_code': 'p154561',
  'minutes': 180,
  'goals_scored': 0,
  'assists': 0,
  'clean_sheets': 2,
  'goals_conceded': 0,
  'own_goals': 0,
  'penalties_saved': 0,
  'penalties_missed': 0,
  'yellow_cards': 0,
  'red_cards': 0,
  'saves': 1,
  'bonus': 0,
  'bps': 45,
  'influence': '17.4',
  'creativity': '0.0',
  'threat': '0.0',
  'ict_index': '1.8',
  'clearances_blocks_interceptions': 2,
  'recoveries': 19,
  'tackles': 0,
  'defensive_contribution': 0,
  'starts': 2,
  'expected_goals': '0.00',
  'expected_assists': '0.00',
  'expected_goal_involvements': '0.00',
  'expected_goals_conceded': '0.53',
  'corners_and_indirect_freekicks_order': None,
  'corners_and_indirect_freekicks_text': '',
  'direct_freekicks_order': None,
  'direct_freekicks_text': '',
  'penalties_order': None,
  'penalties_text': '',
  'scout_risks': [],
  'scout_news_link': '',
  'influence_rank': 194,
  'influence_rank_type': 20,
  'creativity_rank': 631,
  'creativity_rank_type': 71,
  'threat_rank': 626,
  'threat_rank_type': 71,
  'ict_index_rank': 267,
  'ict_index_rank_type': 20,
  'expected_goals_per_90': 0.0,
  'saves_per_90': 0.5,
  'expected_assists_per_90': 0.0,
  'expected_goal_involvements_per_90': 0.0,
  'expected_goals_conceded_per_90': 0.26,
  'goals_conceded_per_90': 0.0,
  'now_cost_rank': 61,
  'now_cost_rank_type': 1,
  'form_rank': 42,
  'form_rank_type': 3,
  'points_per_game_rank': 45,
  'points_per_game_rank_type': 3,
  'selected_rank': 6,
  'selected_rank_type': 1,
  'starts_per_90': 1.0,
  'clean_sheets_per_90': 1.0,
  'defensive_contribution_per_90': 0.0},
 {'can_transact': True,
  'can_select': True,
  'chance_of_playing_next_round': None,
  'chance_of_playing_this_round': None,
  'code': 109745,
  'cost_change_event': 0,
  'cost_change_event_fall': 0,
  'cost_change_start': 0,
  'cost_change_start_fall': 0,
  'price_change_percent': '-93.1',
  'price_change_hourly_rate': 2,
  'price_change_projections': [{'offset': 0,
    'projected_percent': '-91.6',
    'likelihood': -3},
   {'offset': 1, 'projected_percent': '-88.9', 'likelihood': -3},
   {'offset': 2, 'projected_percent': '-86.2', 'likelihood': -3}],
  'price_change_locked_until': None,
  'price_change_calibrating': False,
  'dreamteam_count': 0,
  'element_type': 1,
  'ep_next': '0.0',
  'ep_this': '0.0',
  'event_points': 0,
  'first_name': 'Kepa',
  'form': '0.0',
  'id': 2,
  'in_dreamteam': False,
  'news': '',
  'news_added': None,
  'now_cost': 50,
  'photo': '109745.jpg',
  'points_per_game': '0.0',
  'removed': False,
  'second_name': 'Arrizabalaga Revuelta',
  'selected_by_percent': '0.1',
  'special': False,
  'squad_number': None,
  'status': 'a',
  'team': 1,
  'team_code': 3,
  'total_points': 0,
  'transfers_in': 779,
  'transfers_in_event': 457,
  'transfers_out': 2301,
  'transfers_out_event': 912,
  'value_form': '0.0',
  'value_season': '0.0',
  'web_name': 'Arrizabalaga',
  'known_name': '',
  'region': 200,
  'team_join_date': '2025-07-01',
  'birth_date': '1994-10-03',
  'has_temporary_code': False,
  'opta_code': 'p109745',
  'minutes': 0,
  'goals_scored': 0,
  'assists': 0,
  'clean_sheets': 0,
  'goals_conceded': 0,
  'own_goals': 0,
  'penalties_saved': 0,
  'penalties_missed': 0,
  'yellow_cards': 0,
  'red_cards': 0,
  'saves': 0,
  'bonus': 0,
  'bps': 0,
  'influence': '0.0',
  'creativity': '0.0',
  'threat': '0.0',
  'ict_index': '0.0',
  'clearances_blocks_interceptions': 0,
  'recoveries': 0,
  'tackles': 0,
  'defensive_contribution': 0,
  'starts': 0,
  'expected_goals': '0.00',
  'expected_assists': '0.00',
  'expected_goal_involvements': '0.00',
  'expected_goals_conceded': '0.00',
  'corners_and_indirect_freekicks_order': None,
  'corners_and_indirect_freekicks_text': '',
  'direct_freekicks_order': None,
  'direct_freekicks_text': '',
  'penalties_order': None,
  'penalties_text': '',
  'scout_risks': [],
  'scout_news_link': '',
  'influence_rank': 511,
  'influence_rank_type': 68,
  'creativity_rank': 514,
  'creativity_rank_type': 57,
  'threat_rank': 462,
  'threat_rank_type': 57,
  'ict_index_rank': 520,
  'ict_index_rank_type': 68,
  'expected_goals_per_90': 0,
  'saves_per_90': 0,
  'expected_assists_per_90': 0,
  'expected_goal_involvements_per_90': 0,
  'expected_goals_conceded_per_90': 0,
  'goals_conceded_per_90': 0,
  'now_cost_rank': 245,
  'now_cost_rank_type': 9,
  'form_rank': 528,
  'form_rank_type': 68,
  'points_per_game_rank': 528,
  'points_per_game_rank_type': 68,
  'selected_rank': 456,
  'selected_rank_type': 52,
  'starts_per_90': 0,
  'clean_sheets_per_90': 0,
  'defensive_contribution_per_90': 0},
 {'can_transact': True,
  'can_select': True,
  'chance_of_playing_next_round': None,
  'chance_of_playing_this_round': None,
  'code': 437495,
  'cost_change_event': 0,
  'cost_change_event_fall': 0,
  'cost_change_start': 0,
  'cost_change_start_fall': 0,
  'price_change_percent': '-91.7',
  'price_change_hourly_rate': -1,
  'price_change_projections': [{'offset': 0,
    'projected_percent': '-94.7',
    'likelihood': -3},
   {'offset': 1, 'projected_percent': '-100.0', 'likelihood': -5},
   {'offset': 2, 'projected_percent': '-105.3', 'likelihood': -5}],
  'price_change_locked_until': None,
  'price_change_calibrating': False,
  'dreamteam_count': 0,
  'element_type': 1,
  'ep_next': '0.0',
  'ep_this': '0.0',
  'event_points': 0,
  'first_name': 'Illan',
  'form': '0.0',
  'id': 3,
  'in_dreamteam': False,
  'news': '',
  'news_added': None,
  'now_cost': 50,
  'photo': '437495.jpg',
  'points_per_game': '0.0',
  'removed': False,
  'second_name': 'Meslier',
  'selected_by_percent': '0.0',
  'special': False,
  'squad_number': None,
  'status': 'a',
  'team': 1,
  'team_code': 3,
  'total_points': 0,
  'transfers_in': 227,
  'transfers_in_event': 126,
  'transfers_out': 834,
  'transfers_out_event': 342,
  'value_form': '0.0',
  'value_season': '0.0',
  'web_name': 'Meslier',
  'known_name': '',
  'region': 73,
  'team_join_date': '2026-07-09',
  'birth_date': '2000-03-02',
  'has_temporary_code': False,
  'opta_code': 'p437495',
  'minutes': 0,
  'goals_scored': 0,
  'assists': 0,
  'clean_sheets': 0,
  'goals_conceded': 0,
  'own_goals': 0,
  'penalties_saved': 0,
  'penalties_missed': 0,
  'yellow_cards': 0,
  'red_cards': 0,
  'saves': 0,
  'bonus': 0,
  'bps': 0,
  'influence': '0.0',
  'creativity': '0.0',
  'threat': '0.0',
  'ict_index': '0.0',
  'clearances_blocks_interceptions': 0,
  'recoveries': 0,
  'tackles': 0,
  'defensive_contribution': 0,
  'starts': 0,
  'expected_goals': '0.00',
  'expected_assists': '0.00',
  'expected_goal_involvements': '0.00',
  'expected_goals_conceded': '0.00',
  'corners_and_indirect_freekicks_order': None,
  'corners_and_indirect_freekicks_text': '',
  'direct_freekicks_order': None,
  'direct_freekicks_text': '',
  'penalties_order': None,
  'penalties_text': '',
  'scout_risks': [],
  'scout_news_link': '',
  'influence_rank': 538,
  'influence_rank_type': 70,
  'creativity_rank': 542,
  'creativity_rank_type': 63,
  'threat_rank': 498,
  'threat_rank_type': 63,
  'ict_index_rank': 546,
  'ict_index_rank_type': 70,
  'expected_goals_per_90': 0,
  'saves_per_90': 0,
  'expected_assists_per_90': 0,
  'expected_goal_involvements_per_90': 0,
  'expected_goals_conceded_per_90': 0,
  'goals_conceded_per_90': 0,
  'now_cost_rank': 304,
  'now_cost_rank_type': 15,
  'form_rank': 550,
  'form_rank_type': 70,
  'points_per_game_rank': 550,
  'points_per_game_rank_type': 70,
  'selected_rank': 535,
  'selected_rank_type': 60,
  'starts_per_90': 0,
  'clean_sheets_per_90': 0,
  'defensive_contribution_per_90': 0},
 {'can_transact': True,
  'can_select': True,
  'chance_of_playing_next_round': None,
  'chance_of_playing_this_round': None,
  'code': 226597,
  'cost_change_event': 0,
  'cost_change_event_fall': 0,
  'cost_change_start': 0,
  'cost_change_start_fall': 0,
  'price_change_percent': '-30.2',
  'price_change_hourly_rate': -661,
  'price_change_projections': [{'offset': 0,
    'projected_percent': '-32.2',
    'likelihood': -2},
   {'offset': 1, 'projected_percent': '-35.7', 'likelihood': -2},
   {'offset': 2, 'projected_percent': '-39.2', 'likelihood': -2}],
  'price_change_locked_until': None,
  'price_change_calibrating': False,
  'dreamteam_count': 0,
  'element_type': 2,
  'ep_next': '6.5',
  'ep_this': '6.5',
  'event_points': 8,
  'first_name': 'Gabriel',
  'form': '6.5',
  'id': 4,
  'in_dreamteam': False,
  'news': '',
  'news_added': None,
  'now_cost': 80,
  'photo': '226597.jpg',
  'points_per_game': '6.5',
  'removed': False,
  'second_name': 'dos Santos Magalhães',
  'selected_by_percent': '26.3',
  'special': False,
  'squad_number': None,
  'status': 'a',
  'team': 1,
  'team_code': 3,
  'total_points': 13,
  'transfers_in': 94823,
  'transfers_in_event': 36058,
  'transfers_out': 362075,
  'transfers_out_event': 237967,
  'value_form': '0.8',
  'value_season': '1.6',
  'web_name': 'Gabriel',
  'known_name': 'Gabriel Magalhães',
  'region': 30,
  'team_join_date': '2020-09-01',
  'birth_date': '1997-12-19',
  'has_temporary_code': False,
  'opta_code': 'p226597',
  'minutes': 180,
  'goals_scored': 0,
  'assists': 0,
  'clean_sheets': 2,
  'goals_conceded': 0,
  'own_goals': 0,
  'penalties_saved': 0,
  'penalties_missed': 0,
  'yellow_cards': 1,
  'red_cards': 0,
  'saves': 0,
  'bonus': 0,
  'bps': 44,
  'influence': '24.8',
  'creativity': '5.0',
  'threat': '7.0',
  'ict_index': '3.6',
  'clearances_blocks_interceptions': 12,
  'recoveries': 7,
  'tackles': 2,
  'defensive_contribution': 14,
  'starts': 2,
  'expected_goals': '0.18',
  'expected_assists': '0.03',
  'expected_goal_involvements': '0.21',
  'expected_goals_conceded': '0.53',
  'corners_and_indirect_freekicks_order': None,
  'corners_and_indirect_freekicks_text': '',
  'direct_freekicks_order': None,
  'direct_freekicks_text': '',
  'penalties_order': None,
  'penalties_text': '',
  'scout_risks': [],
  'scout_news_link': '',
  'influence_rank': 154,
  'influence_rank_type': 69,
  'creativity_rank': 210,
  'creativity_rank_type': 67,
  'threat_rank': 182,
  'threat_rank_type': 61,
  'ict_index_rank': 207,
  'ict_index_rank_type': 81,
  'expected_goals_per_90': 0.09,
  'saves_per_90': 0.0,
  'expected_assists_per_90': 0.02,
  'expected_goal_involvements_per_90': 0.11,
  'expected_goals_conceded_per_90': 0.26,
  'goals_conceded_per_90': 0.0,
  'now_cost_rank': 7,
  'now_cost_rank_type': 1,
  'form_rank': 33,
  'form_rank_type': 11,
  'points_per_game_rank': 35,
  'points_per_game_rank_type': 12,
  'selected_rank': 9,
  'selected_rank_type': 2,
  'starts_per_90': 1.0,
  'clean_sheets_per_90': 1.0,
  'defensive_contribution_per_90': 7.0},
 {'can_transact': True,
  'can_select': True,
  'chance_of_playing_next_round': 0,
  'chance_of_playing_this_round': 0,
  'code': 445122,
  'cost_change_event': 0,
  'cost_change_event_fall': 0,
  'cost_change_start': 0,
  'cost_change_start_fall': 0,
  'price_change_percent': '-91.2',
  'price_change_hourly_rate': -1,
  'price_change_projections': [{'offset': 0,
    'projected_percent': '-91.6',
    'likelihood': -3},
   {'offset': 1, 'projected_percent': '-92.3', 'likelihood': -3},
   {'offset': 2, 'projected_percent': '-93.0', 'likelihood': -3}],
  'price_change_locked_until': None,
  'price_change_calibrating': False,
  'dreamteam_count': 0,
  'element_type': 2,
  'ep_next': '0.0',
  'ep_this': '0.0',
  'event_points': 0,
  'first_name': 'Jurriën',
  'form': '0.0',
  'id': 5,
  'in_dreamteam': False,
  'news': 'Groin injury - Unknown return date',
  'news_added': '2026-07-23T12:01:23.272929Z',
  'now_cost': 65,
  'photo': '445122.jpg',
  'points_per_game': '0.0',
  'removed': False,
  'second_name': 'Timber',
  'selected_by_percent': '0.1',
  'special': False,
  'squad_number': None,
  'status': 'i',
  'team': 1,
  'team_code': 3,
  'total_points': 0,
  'transfers_in': 835,
  'transfers_in_event': 434,
  'transfers_out': 5069,
  'transfers_out_event': 1965,
  'value_form': '0.0',
  'value_season': '0.0',
  'web_name': 'J.Timber',
  'known_name': 'Jurriën Timber',
  'region': 152,
  'team_join_date': '2023-07-14',
  'birth_date': '2001-06-17',
  'has_temporary_code': False,
  'opta_code': 'p445122',
  'minutes': 0,
  'goals_scored': 0,
  'assists': 0,
  'clean_sheets': 0,
  'goals_conceded': 0,
  'own_goals': 0,
  'penalties_saved': 0,
  'penalties_missed': 0,
  'yellow_cards': 0,
  'red_cards': 0,
  'saves': 0,
  'bonus': 0,
  'bps': 0,
  'influence': '0.0',
  'creativity': '0.0',
  'threat': '0.0',
  'ict_index': '0.0',
  'clearances_blocks_interceptions': 0,
  'recoveries': 0,
  'tackles': 0,
  'defensive_contribution': 0,
  'starts': 0,
  'expected_goals': '0.00',
  'expected_assists': '0.00',
  'expected_goal_involvements': '0.00',
  'expected_goals_conceded': '0.00',
  'corners_and_indirect_freekicks_order': None,
  'corners_and_indirect_freekicks_text': '',
  'direct_freekicks_order': None,
  'direct_freekicks_text': '',
  'penalties_order': None,
  'penalties_text': '',
  'scout_risks': [],
  'scout_news_link': 'https://www.arsenal.com/news/arteta-issues-update-on-bruno-timber-and-saliba-aKfIr6V2lm7B?utm_source=premier-league-web&utm_medium=referral&utm_campaign=pl-referral-always-on&utm_content=home&utm_term=live-bar',
  'influence_rank': 644,
  'influence_rank_type': 214,
  'creativity_rank': 644,
  'creativity_rank_type': 214,
  'threat_rank': 643,
  'threat_rank_type': 214,
  'ict_index_rank': 644,
  'ict_index_rank_type': 214,
  'expected_goals_per_90': 0,
  'saves_per_90': 0,
  'expected_assists_per_90': 0,
  'expected_goal_involvements_per_90': 0,
  'expected_goals_conceded_per_90': 0,
  'goals_conceded_per_90': 0,
  'now_cost_rank': 40,
  'now_cost_rank_type': 3,
  'form_rank': 643,
  'form_rank_type': 214,
  'points_per_game_rank': 643,
  'points_per_game_rank_type': 214,
  'selected_rank': 441,
  'selected_rank_type': 156,
  'starts_per_90': 0,
  'clean_sheets_per_90': 0,
  'defensive_contribution_per_90': 0},
 {'can_transact': True,
  'can_select': True,
  'chance_of_playing_next_round': 0,
  'chance_of_playing_this_round': 0,
  'code': 462424,
  'cost_change_event': 0,
  'cost_change_event_fall': 0,
  'cost_change_start': 0,
  'cost_change_start_fall': 0,
  'price_change_percent': '-76.8',
  'price_change_hourly_rate': -9,
  'price_change_projections': [{'offset': 0,
    'projected_percent': '-77.9',
    'likelihood': -3},
   {'offset': 1, 'projected_percent': '-79.9', 'likelihood': -3},
   {'offset': 2, 'projected_percent': '-81.8', 'likelihood': -3}],
  'price_change_locked_until': None,
  'price_change_calibrating': False,
  'dreamteam_count': 0,
  'element_type': 2,
  'ep_next': '0.0',
  'ep_this': '0.0',
  'event_points': 0,
  'first_name': 'William',
  'form': '0.0',
  'id': 6,
  'in_dreamteam': False,
  'news': 'Back injury - Unknown return date',
  'news_added': '2026-07-23T12:01:23.289376Z',
  'now_cost': 60,
  'photo': '462424.jpg',
  'points_per_game': '0.0',
  'removed': False,
  'second_name': 'Saliba',
  'selected_by_percent': '0.2',
  'special': False,
  'squad_number': None,
  'status': 'i',
  'team': 1,
  'team_code': 3,
  'total_points': 0,
  'transfers_in': 1811,
  'transfers_in_event': 965,
  'transfers_out': 11446,
  'transfers_out_event': 4630,
  'value_form': '0.0',
  'value_season': '0.0',
  'web_name': 'Saliba',
  'known_name': '',
  'region': 73,
  'team_join_date': '2019-07-25',
  'birth_date': '2001-03-24',
  'has_temporary_code': False,
  'opta_code': 'p462424',
  'minutes': 0,
  'goals_scored': 0,
  'assists': 0,
  'clean_sheets': 0,
  'goals_conceded': 0,
  'own_goals': 0,
  'penalties_saved': 0,
  'penalties_missed': 0,
  'yellow_cards': 0,
  'red_cards': 0,
  'saves': 0,
  'bonus': 0,
  'bps': 0,
  'influence': '0.0',
  'creativity': '0.0',
  'threat': '0.0',
  'ict_index': '0.0',
  'clearances_blocks_interceptions': 0,
  'recoveries': 0,
  'tackles': 0,
  'defensive_contribution': 0,
  'starts': 0,
  'expected_goals': '0.00',
  'expected_assists': '0.00',
  'expected_goal_involvements': '0.00',
  'expected_goals_conceded': '0.00',
  'corners_and_indirect_freekicks_order': None,
  'corners_and_indirect_freekicks_text': '',
  'direct_freekicks_order': None,
  'direct_freekicks_text': '',
  'penalties_order': None,
  'penalties_text': '',
  'scout_risks': [],
  'scout_news_link': 'https://www.arsenal.com/news/arteta-issues-update-on-bruno-timber-and-saliba-aKfIr6V2lm7B?utm_source=premier-league-web&utm_medium=referral&utm_campaign=pl-referral-always-on&utm_content=home&utm_term=live-bar',
  'influence_rank': 633,
  'influence_rank_type': 213,
  'creativity_rank': 634,
  'creativity_rank_type': 213,
  'threat_rank': 629,
  'threat_rank_type': 213,
  'ict_index_rank': 634,
  'ict_index_rank_type': 213,
  'expected_goals_per_90': 0,
  'saves_per_90': 0,
  'expected_assists_per_90': 0,
  'expected_goal_involvements_per_90': 0,
  'expected_goals_conceded_per_90': 0,
  'goals_conceded_per_90': 0,
  'now_cost_rank': 77,
  'now_cost_rank_type': 8,
  'form_rank': 634,
  'form_rank_type': 213,
  'points_per_game_rank': 634,
  'points_per_game_rank_type': 213,
  'selected_rank': 322,
  'selected_rank_type': 119,
  'starts_per_90': 0,
  'clean_sheets_per_90': 0,
  'defensive_contribution_per_90': 0},
 {'can_transact': True,
  'can_select': True,
  'chance_of_playing_next_round': None,
  'chance_of_playing_this_round': None,
  'code': 499169,
  'cost_change_event': 0,
  'cost_change_event_fall': 0,
  'cost_change_start': 0,
  'cost_change_start_fall': 0,
  'price_change_percent': '0.1',
  'price_change_hourly_rate': -18,
  'price_change_projections': [{'offset': 0,
    'projected_percent': '-1.0',
    'likelihood': -1},
   {'offset': 1, 'projected_percent': '-4.6', 'likelihood': -1},
   {'offset': 2, 'projected_percent': '-8.3', 'likelihood': -1}],
  'price_change_locked_until': None,
  'price_change_calibrating': False,
  'dreamteam_count': 0,
  'element_type': 3,
  'ep_next': '3.0',
  'ep_this': '3.0',
  'event_points': 3,
  'first_name': 'Myles',
  'form': '3.0',
  'id': 7,
  'in_dreamteam': False,
  'news': '',
  'news_added': None,
  'now_cost': 55,
  'photo': '499169.jpg',
  'points_per_game': '3.0',
  'removed': False,
  'second_name': 'Lewis-Skelly',
  'selected_by_percent': '0.7',
  'special': False,
  'squad_number': None,
  'status': 'a',
  'team': 1,
  'team_code': 3,
  'total_points': 6,
  'transfers_in': 16463,
  'transfers_in_event': 6770,
  'transfers_out': 18628,
  'transfers_out_event': 9577,
  'value_form': '0.5',
  'value_season': '1.1',

In [10]:
players[0]

{'can_transact': True,
 'can_select': True,
 'chance_of_playing_next_round': None,
 'chance_of_playing_this_round': None,
 'code': 154561,
 'cost_change_event': 0,
 'cost_change_event_fall': 0,
 'cost_change_start': 0,
 'cost_change_start_fall': 0,
 'price_change_percent': '9.4',
 'price_change_hourly_rate': -65,
 'price_change_projections': [{'offset': 0,
   'projected_percent': '8.8',
   'likelihood': 1},
  {'offset': 1, 'projected_percent': '8.0', 'likelihood': 1},
  {'offset': 2, 'projected_percent': '7.1', 'likelihood': 1}],
 'price_change_locked_until': None,
 'price_change_calibrating': False,
 'dreamteam_count': 0,
 'element_type': 1,
 'ep_next': '6.0',
 'ep_this': '6.0',
 'event_points': 6,
 'first_name': 'David',
 'form': '6.0',
 'id': 1,
 'in_dreamteam': False,
 'news': '',
 'news_added': None,
 'now_cost': 60,
 'photo': '154561.jpg',
 'points_per_game': '6.0',
 'removed': False,
 'second_name': 'Raya Martín',
 'selected_by_percent': '37.8',
 'special': False,
 'squad_number': None,
 'status': 'a',
 'team': 1,
 'team_code': 3,
 'total_points': 12,
 'transfers_in': 250451,
 'transfers_in_event': 143717,
 'transfers_out': 234983,
 'transfers_out_event': 153005,
 'value_form': '1.0',
 'value_season': '2.0',
 'web_name': 'Raya',
 'known_name': '',
 'region': 200,
 'team_join_date': '2024-07-04',
 'birth_date': '1995-09-15',
 'has_temporary_code': False,
 'opta_code': 'p154561',
 'minutes': 180,
 'goals_scored': 0,
 'assists': 0,
 'clean_sheets': 2,
 'goals_conceded': 0,
 'own_goals': 0,
 'penalties_saved': 0,
 'penalties_missed': 0,
 'yellow_cards': 0,
 'red_cards': 0,
 'saves': 1,
 'bonus': 0,
 'bps': 45,
 'influence': '17.4',
 'creativity': '0.0',
 'threat': '0.0',
 'ict_index': '1.8',
 'clearances_blocks_interceptions': 2,
 'recoveries': 19,
 'tackles': 0,
 'defensive_contribution': 0,
 'starts': 2,
 'expected_goals': '0.00',
 'expected_assists': '0.00',
 'expected_goal_involvements': '0.00',
 'expected_goals_conceded': '0.53',
 'corners_and_indirect_freekicks_order': None,
 'corners_and_indirect_freekicks_text': '',
 'direct_freekicks_order': None,
 'direct_freekicks_text': '',
 'penalties_order': None,
 'penalties_text': '',
 'scout_risks': [],
 'scout_news_link': '',
 'influence_rank': 194,
 'influence_rank_type': 20,
 'creativity_rank': 631,
 'creativity_rank_type': 71,
 'threat_rank': 626,
 'threat_rank_type': 71,
 'ict_index_rank': 267,
 'ict_index_rank_type': 20,
 'expected_goals_per_90': 0.0,
 'saves_per_90': 0.5,
 'expected_assists_per_90': 0.0,
 'expected_goal_involvements_per_90': 0.0,
 'expected_goals_conceded_per_90': 0.26,
 'goals_conceded_per_90': 0.0,
 'now_cost_rank': 61,
 'now_cost_rank_type': 1,
 'form_rank': 42,
 'form_rank_type': 3,
 'points_per_game_rank': 45,
 'points_per_game_rank_type': 3,
 'selected_rank': 6,
 'selected_rank_type': 1,
 'starts_per_90': 1.0,
 'clean_sheets_per_90': 1.0,
 'defensive_contribution_per_90': 0.0}

In [38]:
player_keys = {
    "id": int,
    "code": int,
    "opta_code": str,
    "web_name": str,
    "second_name": str,
    "first_name": str,
    "ep_next": float,
    "ep_this": float
}

In [39]:
df = pl.from_dicts(players, schema=player_keys)

In [66]:
df_ep = df.with_columns(
    (pl.col("ep_next") - pl.col("ep_this")).alias('ep_change')
).with_columns(
    pl.col('ep_change').sign().alias("sign")
)

In [67]:
df_ep.group_by("sign").len()

shape: (3, 2)
┌──────┬─────┐
│ sign ┆ len │
│ ---  ┆ --- │
│ f64  ┆ u32 │
╞══════╪═════╡
│ -1.0 ┆ 14  │
│ 0.0  ┆ 630 │
│ 1.0  ┆ 7   │
└──────┴─────┘

In [68]:
pl.Config.set_tbl_rows(50)

polars.config.Config

In [73]:
df_ep.filter(pl.col("web_name").str.contains("Haa"))

shape: (1, 10)
┌─────┬────────┬───────────┬──────────┬───┬─────────┬─────────┬───────────┬──────┐
│ id  ┆ code   ┆ opta_code ┆ web_name ┆ … ┆ ep_next ┆ ep_this ┆ ep_change ┆ sign │
│ --- ┆ ---    ┆ ---       ┆ ---      ┆   ┆ ---     ┆ ---     ┆ ---       ┆ ---  │
│ i64 ┆ i64    ┆ str       ┆ str      ┆   ┆ f64     ┆ f64     ┆ f64       ┆ f64  │
╞═════╪════════╪═══════════╪══════════╪═══╪═════════╪═════════╪═══════════╪══════╡
│ 411 ┆ 223094 ┆ p223094   ┆ Haaland  ┆ … ┆ 7.5     ┆ 7.5     ┆ 0.0       ┆ 0.0  │
└─────┴────────┴───────────┴──────────┴───┴─────────┴─────────┴───────────┴──────┘

In [72]:
df_ep.sort("ep_next", descending=True)

shape: (651, 10)
┌─────┬────────┬───────────┬──────────────────┬───┬─────────┬─────────┬───────────┬──────┐
│ id  ┆ code   ┆ opta_code ┆ web_name         ┆ … ┆ ep_next ┆ ep_this ┆ ep_change ┆ sign │
│ --- ┆ ---    ┆ ---       ┆ ---              ┆   ┆ ---     ┆ ---     ┆ ---       ┆ ---  │
│ i64 ┆ i64    ┆ str       ┆ str              ┆   ┆ f64     ┆ f64     ┆ f64       ┆ f64  │
╞═════╪════════╪═══════════╪══════════════════╪═══╪═════════╪═════════╪═══════════╪══════╡
│ 426 ┆ 141746 ┆ p141746   ┆ B.Fernandes      ┆ … ┆ 12.5    ┆ 12.5    ┆ 0.0       ┆ 0.0  │
│ 399 ┆ 466052 ┆ p466052   ┆ Cherki           ┆ … ┆ 11.0    ┆ 11.0    ┆ 0.0       ┆ 0.0  │
│ 8   ┆ 466075 ┆ p466075   ┆ Calafiori        ┆ … ┆ 10.0    ┆ 10.0    ┆ 0.0       ┆ 0.0  │
│ 12  ┆ 223340 ┆ p223340   ┆ Saka             ┆ … ┆ 10.0    ┆ 10.0    ┆ 0.0       ┆ 0.0  │
│ 154 ┆ 244851 ┆ p244851   ┆ Palmer           ┆ … ┆ 10.0    ┆ 10.0    ┆ 0.0       ┆ 0.0  │
│ 165 ┆ 475168 ┆ p475168   ┆ João Pedro       ┆ … ┆ 10.0    ┆ 10.0    ┆ 0.0       ┆ 0.0  │
│ 279 ┆ 146426 ┆ p146426   ┆ Ajayi            ┆ … ┆ 10.0    ┆ 10.0    ┆ 0.0       ┆ 0.0  │
│ 572 ┆ 473284 ┆ p473284   ┆ Tzolakis         ┆ … ┆ 10.0    ┆ 10.0    ┆ 0.0       ┆ 0.0  │
│ 10  ┆ 198869 ┆ p198869   ┆ White            ┆ … ┆ 9.0     ┆ 9.0     ┆ 0.0       ┆ 0.0  │
│ 565 ┆ 513545 ┆ p513545   ┆ M.Sangaré        ┆ … ┆ 9.0     ┆ 9.0     ┆ 0.0       ┆ 0.0  │
│ 229 ┆ 17761  ┆ p17761    ┆ Tarkowski        ┆ … ┆ 9.0     ┆ 9.0     ┆ 0.0       ┆ 0.0  │
│ 115 ┆ 465730 ┆ p465730   ┆ De Cuyper        ┆ … ┆ 8.5     ┆ 8.5     ┆ 0.0       ┆ 0.0  │
│ 277 ┆ 108416 ┆ p108416   ┆ Egan             ┆ … ┆ 8.5     ┆ 8.5     ┆ 0.0       ┆ 0.0  │
│ 335 ┆ 466525 ┆ p466525   ┆ Stach            ┆ … ┆ 8.5     ┆ 8.5     ┆ 0.0       ┆ 0.0  │
│ 367 ┆ 243298 ┆ p243298   ┆ Gakpo            ┆ … ┆ 8.5     ┆ 8.5     ┆ 0.0       ┆ 0.0  │
│ 454 ┆ 449434 ┆ p449434   ┆ Elanga           ┆ … ┆ 8.5     ┆ 8.5     ┆ 0.0       ┆ 0.0  │
│ 86  ┆ 249231 ┆ p249231   ┆ Lewis-Potter     ┆ … ┆ 8.0     ┆ 8.0     ┆ 0.0       ┆ 0.0  │
│ 586 ┆ 606930 ┆ p606930   ┆ Mendy            ┆ … ┆ 8.0     ┆ 8.0     ┆ 0.0       ┆ 0.0  │
│ 88  ┆ 607464 ┆ p607464   ┆ Kayode           ┆ … ┆ 7.5     ┆ 7.5     ┆ 0.0       ┆ 0.0  │
│ 124 ┆ 60307  ┆ p60307    ┆ Groß             ┆ … ┆ 7.5     ┆ 7.5     ┆ 0.0       ┆ 0.0  │
│ 411 ┆ 223094 ┆ p223094   ┆ Haaland          ┆ … ┆ 7.5     ┆ 7.5     ┆ 0.0       ┆ 0.0  │
│ 480 ┆ 222531 ┆ p222531   ┆ Gibbs-White      ┆ … ┆ 7.5     ┆ 7.5     ┆ 0.0       ┆ 0.0  │
│ 544 ┆ 84450  ┆ p84450    ┆ Xhaka            ┆ … ┆ 7.5     ┆ 7.5     ┆ 0.0       ┆ 0.0  │
│ 15  ┆ 184029 ┆ p184029   ┆ Ødegaard         ┆ … ┆ 7.0     ┆ 7.0     ┆ 0.0       ┆ 0.0  │
│ 69  ┆ 503139 ┆ p503139   ┆ Scott            ┆ … ┆ 7.0     ┆ 7.0     ┆ 0.0       ┆ 0.0  │
│ …   ┆ …      ┆ …         ┆ …                ┆ … ┆ …       ┆ …       ┆ …         ┆ …    │
│ 500 ┆ 221632 ┆ p221632   ┆ Romero           ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
│ 503 ┆ 491279 ┆ p491279   ┆ Van de Ven       ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
│ 505 ┆ 232859 ┆ p232859   ┆ Spence           ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
│ 507 ┆ 548308 ┆ p548308   ┆ Phillips         ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
│ 508 ┆ 115556 ┆ p115556   ┆ Davies           ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
│ 509 ┆ 640419 ┆ p640419   ┆ Byfield          ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
│ 510 ┆ 499716 ┆ p499716   ┆ Rowswell         ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
│ 511 ┆ 616221 ┆ p616221   ┆ Souza            ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
│ 513 ┆ 493362 ┆ p493362   ┆ Xavi             ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
│ 517 ┆ 550839 ┆ p550839   ┆ Odobert          ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
│ 518 ┆ 482442 ┆ p482442   ┆ P.M.Sarr         ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
│ 519 ┆ 232787 ┆ p232787   ┆ Gallagher        ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
│ 521 ┆ 445044 ┆ p445044   ┆ Kulusevski       ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
│ 524 ┆ 499726 ┆ p499726   ┆ Olusesi          ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
│ 528 ┆ 490145 ┆ p490145   ┆ Scarlett         ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
│ 578 ┆ 465920 ┆ p465920   ┆ Mudryk           ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
│ 601 ┆ 611917 ┆ p611917   ┆ Williams-Barnett ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
│ 501 ┆ 135720 ┆ p135720   ┆ Danso            ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
│ 530 ┆ 232571 ┆ p232571   ┆ Patterson        ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
│ 531 ┆ 515046 ┆ p515046   ┆ Ellborg          ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
│ 537 ┆ 519634 ┆ p519634   ┆ Seelt            ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
│ 538 ┆ 477547 ┆ p477547   ┆ Hjelde           ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
│ 540 ┆ 105717 ┆ p105717   ┆ Masuaku          ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
│ 546 ┆ 535818 ┆ p535818   ┆ Adingra          ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
│ 550 ┆ 699989 ┆ p699989   ┆ Jocelin.T        ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0       ┆ 0.0  │
└─────┴────────┴───────────┴──────────────────┴───┴─────────┴─────────┴───────────┴──────┘

In [70]:
df_ep.filter(pl.col("sign") < 0 )

shape: (14, 10)
┌─────┬────────┬───────────┬────────────────┬───┬─────────┬─────────┬───────────┬──────┐
│ id  ┆ code   ┆ opta_code ┆ web_name       ┆ … ┆ ep_next ┆ ep_this ┆ ep_change ┆ sign │
│ --- ┆ ---    ┆ ---       ┆ ---            ┆   ┆ ---     ┆ ---     ┆ ---       ┆ ---  │
│ i64 ┆ i64    ┆ str       ┆ str            ┆   ┆ f64     ┆ f64     ┆ f64       ┆ f64  │
╞═════╪════════╪═══════════╪════════════════╪═══╪═════════╪═════════╪═══════════╪══════╡
│ 97  ┆ 207283 ┆ p207283   ┆ Jensen         ┆ … ┆ 2.2     ┆ 3.0     ┆ -0.8      ┆ -1.0 │
│ 129 ┆ 509416 ┆ p509416   ┆ Ayari          ┆ … ┆ 0.8     ┆ 1.0     ┆ -0.2      ┆ -1.0 │
│ 624 ┆ 519324 ┆ p519324   ┆ Cozier-Duberry ┆ … ┆ 0.0     ┆ 1.5     ┆ -1.5      ┆ -1.0 │
│ 140 ┆ 215059 ┆ p215059   ┆ Sánchez        ┆ … ┆ 0.0     ┆ 1.0     ┆ -1.0      ┆ -1.0 │
│ 223 ┆ 231747 ┆ p231747   ┆ Mateta         ┆ … ┆ 0.0     ┆ 1.0     ┆ -1.0      ┆ -1.0 │
│ 248 ┆ 486385 ┆ p486385   ┆ Beto           ┆ … ┆ 0.0     ┆ 1.0     ┆ -1.0      ┆ -1.0 │
│ 280 ┆ 193278 ┆ p193278   ┆ Coyle          ┆ … ┆ 2.2     ┆ 3.0     ┆ -0.8      ┆ -1.0 │
│ 281 ┆ 433590 ┆ p433590   ┆ Drameh         ┆ … ┆ 0.0     ┆ 1.0     ┆ -1.0      ┆ -1.0 │
│ 287 ┆ 232905 ┆ p232905   ┆ Millar         ┆ … ┆ 0.0     ┆ 3.0     ┆ -3.0      ┆ -1.0 │
│ 289 ┆ 101282 ┆ p101282   ┆ Crooks         ┆ … ┆ 0.8     ┆ 1.0     ┆ -0.2      ┆ -1.0 │
│ 316 ┆ 543968 ┆ p543968   ┆ Emersonn       ┆ … ┆ 3.8     ┆ 5.0     ┆ -1.2      ┆ -1.0 │
│ 329 ┆ 214225 ┆ p214225   ┆ Rodon          ┆ … ┆ 1.8     ┆ 3.5     ┆ -1.7      ┆ -1.0 │
│ 463 ┆ 470313 ┆ p470313   ┆ Woltemade      ┆ … ┆ 0.0     ┆ 2.0     ┆ -2.0      ┆ -1.0 │
│ 543 ┆ 547027 ┆ p547027   ┆ Diarra         ┆ … ┆ 1.9     ┆ 2.5     ┆ -0.6      ┆ -1.0 │
└─────┴────────┴───────────┴────────────────┴───┴─────────┴─────────┴───────────┴──────┘

In [41]:
df.select(
    pl.col("web_name"),
    pl.col("ep_next"),
    pl.col("ep_this"),
    (pl.col("ep_this") - pl.col("ep_next")).alias('ep_change')
)

shape: (651, 4)
┌──────────────┬─────────┬─────────┬───────────┐
│ web_name     ┆ ep_next ┆ ep_this ┆ ep_change │
│ ---          ┆ ---     ┆ ---     ┆ ---       │
│ str          ┆ f64     ┆ f64     ┆ f64       │
╞══════════════╪═════════╪═════════╪═══════════╡
│ Raya         ┆ 6.0     ┆ 6.0     ┆ 0.0       │
│ Arrizabalaga ┆ 0.0     ┆ 0.0     ┆ 0.0       │
│ Meslier      ┆ 0.0     ┆ 0.0     ┆ 0.0       │
│ Gabriel      ┆ 6.5     ┆ 6.5     ┆ 0.0       │
│ J.Timber     ┆ 0.0     ┆ 0.0     ┆ 0.0       │
│ …            ┆ …       ┆ …       ┆ …         │
│ Isidor       ┆ 4.5     ┆ 4.5     ┆ 0.0       │
│ Methalie     ┆ 1.8     ┆ 0.0     ┆ -1.8      │
│ Ahoka        ┆ 1.0     ┆ 1.0     ┆ 0.0       │
│ Fofana       ┆ 2.0     ┆ 2.0     ┆ 0.0       │
│ J.Angulo     ┆ 1.0     ┆ 1.0     ┆ 0.0       │
└──────────────┴─────────┴─────────┴───────────┘

In [ ]:
pl

In [12]:
game_config = data["game_config"]
game_config

{'settings': {'entry_per_event': False,
  'timezone': 'UTC',
  'static_content_url': 'https://fantasy.premierleague.com/gcs/plfpl-prod-static-content/plfpl-production/2026_27/',
  'price_change_deadlines': ['2026-09-03T23:00:00Z',
   '2026-09-04T23:00:00Z',
   '2026-09-05T23:00:00Z']},
 'rules': {'league_join_private_max': 30,
  'league_join_public_max': 5,
  'league_max_size_public_classic': 20,
  'league_max_size_public_h2h': 20,
  'league_max_size_private_h2h': 16,
  'league_max_ko_rounds_private_h2h': 3,
  'league_prefix_public': 'League',
  'league_points_h2h_win': 3,
  'league_points_h2h_lose': 0,
  'league_points_h2h_draw': 1,
  'league_ko_first_instead_of_random': False,
  'cup_start_event_id': None,
  'cup_stop_event_id': None,
  'cup_qualifying_method': None,
  'cup_type': None,
  'featured_entries': [],
  'element_sell_at_purchase_price': False,
  'percentile_ranks': [1,
   5,
   10,
   15,
   20,
   25,
   30,
   35,
   40,
   45,
   50,
   55,
   60,
   65,
   70,
   75,
   80,
   85,
   90,
   95],
  'underdog_differential': 5,
  'squad_squadplay': 11,
  'squad_squadsize': 15,
  'squad_special_min': None,
  'squad_special_max': None,
  'squad_team_limit': 3,
  'squad_total_spend': 1000,
  'ui_currency_multiplier': 10,
  'ui_use_special_shirts': False,
  'ui_special_shirt_exclusions': [],
  'stats_form_days': 30,
  'sys_vice_captain_enabled': True,
  'transfers_cap': 20,
  'transfers_sell_on_fee': 0.5,
  'max_extra_free_transfers': 4,
  'league_h2h_tiebreak_stats': ['+goals_scored', '-goals_conceded']},
 'scoring': {'long_play': 2,
  'short_play': 1,
  'goals_conceded': {'DEF': -1, 'FWD': 0, 'GKP': -1, 'MID': 0},
  'saves': 1,
  'goals_scored': {'DEF': 6, 'FWD': 4, 'GKP': 10, 'MID': 5},
  'assists': 3,
  'clean_sheets': {'DEF': 4, 'FWD': 0, 'GKP': 4, 'MID': 1},
  'penalties_saved': 5,
  'penalties_missed': -2,
  'yellow_cards': -1,
  'red_cards': -3,
  'own_goals': -2,
  'bonus': 1,
  'bps': 0,
  'influence': 0,
  'creativity': 0,
  'threat': 0,
  'ict_index': 0,
  'special_multiplier': 1,
  'tackles': 0,
  'clearances_blocks_interceptions': 0,
  'recoveries': 0,
  'defensive_contribution': {'DEF': 2, 'FWD': 2, 'GKP': 0, 'MID': 2},
  'starts': 0,
  'mng_goals_scored': {'DEF': 0, 'FWD': 0, 'GKP': 0, 'MID': 0},
  'mng_clean_sheets': {'DEF': 0, 'FWD': 0, 'GKP': 0, 'MID': 0},
  'mng_win': {'DEF': 0, 'FWD': 0, 'GKP': 0, 'MID': 0},
  'mng_draw': {'DEF': 0, 'FWD': 0, 'GKP': 0, 'MID': 0},
  'mng_loss': 0,
  'mng_underdog_win': {'DEF': 0, 'FWD': 0, 'GKP': 0, 'MID': 0},
  'mng_underdog_draw': {'DEF': 0, 'FWD': 0, 'GKP': 0, 'MID': 0},
  'expected_assists': 0,
  'expected_goal_involvements': 0,
  'expected_goals_conceded': 0,
  'expected_goals': 0}}